version: "3.9"
services:
  postgres-docker:
    image: postgres:18-alpine
    container_name: postgres-container
    environment:
      POSTGRES_DB: basicdatabase
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network

  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: usuario@pokemail.net
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 5050:80
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres-docker
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge