spring:
  datasource:
    url: jdbc:postgresql://dpg-d5lc46koud1c738jp1g0-a.oregon-postgres.render.com:5432/tododb
    username: basicdatabase_8ht8_user
    password: Ohp2Pb3WB0fzetepC538ZzhkpxNRCf92
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    duration: ${DURATION}